### ISSUE TITLE
Is the embedded IZipLib necessary?

### ISSUE THREAD

**Issue by tekhedd** [RipcordSoftware/HttpWebServer#1]
Is there a strong reason not to use the GZipLib support supplied with the framework on mono/.net?

Not sure whether this is a bug report, enhancement request, or just a question. :)

**Comment by craigminihan** [comment]
I somehow missed this issue. 

As of fca1c88f3b949787613d0c1773e55fce9873f95f dotnetzip is included via nuget. The reason that the built in gzip isn't used is performance.
